be_happy_rights_management_group_crud_paths:
    resource: |
        alias: be_happy_rights_management.group
        except: [ 'show' ]
        section: admin
        templates: "@BeHappySyliusRightsManagementPlugin\\Admin\\Group"
        grid: be_happy_rights_management_group
        vars:
            all:
                templates:
                    form: "@BeHappySyliusRightsManagementPlugin\\Admin\\Group\\_form.html.twig"
    type: sylius.resource
    prefix: /admin
